#!/usr/bin/env python
# coding: utf-8
"""Cross-profile comparison report.

Reads the per-section text and audit JSONs across all (profile, ticker) cells
and produces a comparison table:

  - section length (chars / words)
  - critic verdict (ACCEPT / REVISE / MAJOR_REVISE / -)
  - whether a revise pass actually fired
  - number of distinct numeric figures cited (a rough analytical-density proxy)

Output:
  output/experiments/comparison.json   raw stats per (profile, ticker, section)
  output/experiments/comparison.md     human-readable Markdown summary

Usage:
  cd finrobot_equity
  python scripts/compare_outputs.py
"""

from __future__ import annotations

import json
import os
import re
from collections import defaultdict
from pathlib import Path
from statistics import mean
from typing import Dict, List, Optional


THIS_DIR = Path(__file__).resolve().parent
EQUITY_ROOT = THIS_DIR.parent
EXPERIMENTS_DIR = EQUITY_ROOT / "core" / "output" / "experiments"

PROFILES = ["gpt_baseline", "claude_all", "gemini_all", "mixed_critic"]
TICKERS = ["NVDA", "AMD", "INTC", "AAPL", "GOOGL"]
SECTIONS = [
    "tagline", "company_overview", "investment_overview", "valuation_overview",
    "risks", "competitor_analysis", "major_takeaways", "news_summary",
]
HEAVY_SECTIONS = {"company_overview", "investment_overview", "valuation_overview", "risks", "competitor_analysis"}
CRITIQUE_SECTIONS = {"investment_overview", "risks", "valuation_overview"}


# Match $1.2B, 12.3%, 2024A, 130.5, 36.0x, etc.
NUMBER_RE = re.compile(
    r"(?:[\$])?\d+(?:[.,]\d+)?(?:[%xX]|\s?(?:billion|million|trillion|B|M|bps))?"
    r"|(?:19|20)\d{2}[AE]?",
    re.IGNORECASE,
)


def load_audit(profile: str, ticker: str, section: str) -> Optional[Dict]:
    p = EXPERIMENTS_DIR / profile / ticker / "audit" / f"{section}.audit.json"
    if not p.exists():
        return None
    try:
        return json.load(open(p))
    except Exception:
        return None


def load_section_text(profile: str, ticker: str, section: str) -> str:
    p = EXPERIMENTS_DIR / profile / ticker / "analysis" / f"{section}.txt"
    if not p.exists():
        return ""
    try:
        return p.read_text(encoding="utf-8")
    except Exception:
        return ""


def figure_density(text: str) -> int:
    """Rough proxy for analytical density: count distinct numeric tokens."""
    if not text:
        return 0
    matches = NUMBER_RE.findall(text)
    return len(set(matches))


def build_stats() -> Dict:
    stats = {"cells": [], "by_profile": defaultdict(lambda: defaultdict(list))}
    for prof in PROFILES:
        for tk in TICKERS:
            cell = {"profile": prof, "ticker": tk, "sections": {}}
            cell_dir = EXPERIMENTS_DIR / prof / tk
            if not cell_dir.exists():
                stats["cells"].append(cell)
                continue

            for sec in SECTIONS:
                text = load_section_text(prof, tk, sec)
                audit = load_audit(prof, tk, sec) or {}
                entry = {
                    "chars": len(text),
                    "words": len(text.split()),
                    "figures": figure_density(text),
                    "author_model": audit.get("author_model"),
                    "critic_model": audit.get("critic_model"),
                    "verdict": audit.get("verdict"),
                    "revised": "revised" in audit,
                }
                cell["sections"][sec] = entry

                stats["by_profile"][prof]["chars"].append(entry["chars"])
                stats["by_profile"][prof]["words"].append(entry["words"])
                stats["by_profile"][prof]["figures"].append(entry["figures"])
                if sec in CRITIQUE_SECTIONS and entry["verdict"]:
                    stats["by_profile"][prof].setdefault("verdicts", []).append(entry["verdict"])
            stats["cells"].append(cell)

    # Materialize defaultdicts
    out = {"cells": stats["cells"], "by_profile": {}}
    for prof, agg in stats["by_profile"].items():
        out["by_profile"][prof] = {
            "avg_chars": round(mean(agg["chars"]), 1) if agg["chars"] else 0,
            "avg_words": round(mean(agg["words"]), 1) if agg["words"] else 0,
            "avg_figures": round(mean(agg["figures"]), 1) if agg["figures"] else 0,
            "verdicts": _verdict_counts(agg.get("verdicts", [])),
            "n_sections": len(agg["chars"]),
        }
    return out


def _verdict_counts(verdicts: List[str]) -> Dict[str, int]:
    out = defaultdict(int)
    for v in verdicts:
        out[v] += 1
    return dict(out)


def render_markdown(stats: Dict) -> str:
    lines = []
    lines.append("# FinRobot Assignment 2 — Cross-Profile Comparison\n")
    lines.append("Generated by `scripts/compare_outputs.py`. "
                 "Compares text outputs across the 4 model-routing profiles.\n")

    # ---- Profile-level summary
    lines.append("## Profile-level averages\n")
    lines.append("| Profile | Avg chars/section | Avg words/section | Avg figures cited | Critic verdicts (3 sections × 5 tickers) |")
    lines.append("|---|---:|---:|---:|---|")
    for prof in PROFILES:
        if prof not in stats["by_profile"]:
            continue
        s = stats["by_profile"][prof]
        verdicts = s.get("verdicts", {}) or {}
        verdict_str = ", ".join(f"{k}: {v}" for k, v in sorted(verdicts.items())) or "—"
        lines.append(f"| {prof} | {s['avg_chars']} | {s['avg_words']} | {s['avg_figures']} | {verdict_str} |")
    lines.append("")

    # ---- Per-section, per-profile chars matrix
    lines.append("## Section length matrix (chars)\n")
    header = "| Ticker / Section |" + "|".join(f" {p[:10]} " for p in PROFILES) + "|"
    sep    = "|---|" + "|".join("---:" for _ in PROFILES) + "|"
    for sec in SECTIONS:
        lines.append(f"### {sec}\n")
        lines.append(header)
        lines.append(sep)
        for tk in TICKERS:
            row = [f"| {tk}"]
            for prof in PROFILES:
                cell = next((c for c in stats["cells"] if c["profile"] == prof and c["ticker"] == tk), None)
                v = (cell or {}).get("sections", {}).get(sec, {}).get("chars", 0)
                row.append(str(v))
            lines.append(" | ".join(row) + " |")
        lines.append("")

    # ---- Critic verdicts per cell
    lines.append("## Critic verdicts (only profiles with critique enabled)\n")
    lines.append("| Profile | Ticker | investment_overview | risks | valuation_overview |")
    lines.append("|---|---|---|---|---|")
    for prof in [p for p in PROFILES if p != "gpt_baseline"]:
        for tk in TICKERS:
            row = [prof, tk]
            for sec in ["investment_overview", "risks", "valuation_overview"]:
                cell = next((c for c in stats["cells"] if c["profile"] == prof and c["ticker"] == tk), None)
                e = (cell or {}).get("sections", {}).get(sec, {})
                v = e.get("verdict") or "-"
                if e.get("revised"):
                    v = f"{v}→revised"
                row.append(v)
            lines.append("| " + " | ".join(row) + " |")
    lines.append("")

    # ---- Figure-density matrix (heavy sections only)
    lines.append("## Numeric figures cited per section (proxy for analytical density)\n")
    lines.append("Higher is generally better — sections that name specific numbers are more analytically grounded than vague prose.\n")
    lines.append("| Section / Profile |" + "|".join(f" {p[:10]} " for p in PROFILES) + "|")
    lines.append("|---|" + "|".join("---:" for _ in PROFILES) + "|")
    for sec in sorted(HEAVY_SECTIONS):
        row = [sec]
        for prof in PROFILES:
            vals = []
            for tk in TICKERS:
                cell = next((c for c in stats["cells"] if c["profile"] == prof and c["ticker"] == tk), None)
                e = (cell or {}).get("sections", {}).get(sec, {})
                if e.get("figures") is not None:
                    vals.append(e["figures"])
            avg = round(mean(vals), 1) if vals else 0
            row.append(str(avg))
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")

    return "\n".join(lines)


def main():
    if not EXPERIMENTS_DIR.exists():
        raise SystemExit(f"experiments dir not found: {EXPERIMENTS_DIR}")
    stats = build_stats()
    json_path = EXPERIMENTS_DIR / "comparison.json"
    md_path = EXPERIMENTS_DIR / "comparison.md"
    json_path.write_text(json.dumps(stats, indent=2, default=str))
    md_path.write_text(render_markdown(stats))
    print(f"Wrote: {json_path}")
    print(f"Wrote: {md_path}")


if __name__ == "__main__":
    main()
